// Code generated by sqlc. DO NOT EDIT.
// source: thread_queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (id, title, description)
VALUES ($1, $2, $3)
RETURNING id, title, description
`

type CreateThreadParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread, arg.ID, arg.Title, arg.Description)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads
WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteThread, id)
	return err
}

const getThread = `-- name: GetThread :one
SELECT id, title, description FROM threads
WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id uuid.UUID) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getThreads = `-- name: GetThreads :many
SELECT id, title, description FROM threads
`

func (q *Queries) GetThreads(ctx context.Context) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, getThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThread = `-- name: UpdateThread :one
UPDATE threads
SET title = $1, description = $2
WHERE id = $3
RETURNING id, title, description
`

type UpdateThreadParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, updateThread, arg.Title, arg.Description, arg.ID)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}
