// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"github.com/google/uuid"
)

type Comment struct {
	ID      uuid.UUID `json:"id"`
	PostID  uuid.UUID `json:"post_id"`
	Content string    `json:"content"`
	Votes   int32     `json:"votes"`
}

type Post struct {
	ID       uuid.UUID `json:"id"`
	ThreadID uuid.UUID `json:"thread_id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	Votes    int32     `json:"votes"`
}

type Thread struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

type Todo struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Task   string    `json:"task"`
	Done   bool      `json:"done"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
}
